In [ ]:
1. Getting Familiar with NumPy

In [15]:
import numpy as np

# Creating and displaying arrays
array_1d = np.array([1, 2, 3, 4, 5])
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

# Performing basic operations
array_sum = array_1d + 10
array_product = array_2d * 2

print("\nArray after adding 10 to each element:")
print(array_sum)

print("\nArray after multiplying each element by 2:")
print(array_product)

# Displaying array properties
print("\nArray Properties:")
print(f"Shape of array_2d: {array_2d.shape}")
print(f"Size of array_2d: {array_2d.size}")
print(f"Data type of array_2d: {array_2d.dtype}")


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]

Array after adding 10 to each element:
[11 12 13 14 15]

Array after multiplying each element by 2:
[[ 2  4  6]
 [ 8 10 12]]

Array Properties:
Shape of array_2d: (2, 3)
Size of array_2d: 6
Data type of array_2d: int64


In [ ]:
2. Data Manipulation with NumPy

In [16]:
# Array creation and manipulation
array = np.arange(10)

print("\nArray created with arange:")
print(array)

# Indexing and slicing
print("\nElement at index 5:")
print(array[5])

print("\nSliced array (elements from index 2 to 5):")
print(array[2:6])

# Reshaping arrays
array_reshaped = array.reshape((2, 5))

print("\nReshaped array (2x5):")
print(array_reshaped)

# Applying mathematical operations
array_squared = np.square(array)
array_sqrt = np.sqrt(array)

print("\nArray after squaring each element:")
print(array_squared)

print("\nSquare root of each element in the array:")
print(array_sqrt)



Array created with arange:
[0 1 2 3 4 5 6 7 8 9]

Element at index 5:
5

Sliced array (elements from index 2 to 5):
[2 3 4 5]

Reshaped array (2x5):
[[0 1 2 3 4]
 [5 6 7 8 9]]

Array after squaring each element:
[ 0  1  4  9 16 25 36 49 64 81]

Square root of each element in the array:
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [ ]:
3. Data Aggregation

In [17]:
# Creating a 2D array for aggregation
data = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print("\nData Array:")
print(data)

# Computing summary statistics
mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
total_sum = np.sum(data)

print("\nSummary Statistics:")
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Standard Deviation: {std_dev}")
print(f"Sum: {total_sum}")

# Filtering data
above_mean = data[data > mean]

print("\nElements Above Mean:")
print(above_mean)



Data Array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]

Summary Statistics:
Mean: 50.0
Median: 50.0
Standard Deviation: 25.81988897471611
Sum: 450

Elements Above Mean:
[60 70 80 90]


In [ ]:
4. Data Analysis

In [18]:
# Correlation example
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

correlation = np.corrcoef(x, y)

print("\nCorrelation Coefficient between x and y:")
print(correlation)

# Identifying outliers using Z-scores
data_with_outliers = np.array([10, 12, 15, 18, 20, 22, 100])
mean_data = np.mean(data_with_outliers)
std_dev_data = np.std(data_with_outliers)
z_scores = (data_with_outliers - mean_data) / std_dev_data

print("\nZ-Scores of the Data (Detect Outliers):")
print(z_scores)

outliers = data_with_outliers[np.abs(z_scores) > 2]

print("\nOutliers in the Data:")
print(outliers)

# Calculating percentiles
percentile_25 = np.percentile(data_with_outliers, 25)
percentile_50 = np.percentile(data_with_outliers, 50)
percentile_75 = np.percentile(data_with_outliers, 75)

print("\nPercentiles of the Data:")
print(f"25th Percentile: {percentile_25}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"75th Percentile: {percentile_75}")



Correlation Coefficient between x and y:
[[1. 1.]
 [1. 1.]]

Z-Scores of the Data (Detect Outliers):
[-0.6129475  -0.54537848 -0.44402496 -0.34267144 -0.27510242 -0.2075334
  2.4276582 ]

Outliers in the Data:
[100]

Percentiles of the Data:
25th Percentile: 13.5
50th Percentile (Median): 18.0
75th Percentile: 21.0


In [ ]:
Application in Data Science
Advantages of Using NumPy:

Performance: Realization of operations with a large array of elements.
Ease of Use: Helps to solve complicated mathematical problems.
Integration: Compliments other libraries such as Pandas, Scikit-Learn, and SciPy.
Handling Large Datasets: Designed for handling very large data sets.
undefined

Machine Learning: Used for mathematical computations and matrix calculations.
Financial Analysis: For carrying out calculation of indicators and modeling of data.
Scientific Research: For simulations and permutations and combinations of questions in mathematics.
undefined
NumPy is the fundamental package in Python for high-performance numerical computation. It allows creating arrays, solving mathematical, summing and grouping problems, and doing statistical calculations, which makes it extremely useful for data scientists who work with large amount of data and complex calculations.